name: Actions workflow

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo "${{ github.token}}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git Checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after checkput
        run: |
          pwd
          ls -a

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rene
      - name: Log greeting Time for JS action
        run: echo "${{ steps.greet.outputs.time}}"